name: Node.js CI

on:
  push:
    branches: [ "APM-01" ]
  pull_request:
    branches: [ "APM-01" ]

jobs:
  build_and_deploy_main:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Pull and build App for PROD
        uses: appleboy/ssh-action@master
        with:
          script: |
            set -e
            cd /var/www/amp-scanner/frontend/
            cat script.sh
          host: 31.210.50.186
          username: root
          password: 12A6WFC73EA637xGq93*k- 
